"""add classification, sentiment, geocoding, review workflow

Revision ID: 050acc66ee28
Revises: 61139cf4b2d1
Create Date: 2026-07-28 15:15:34.431924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '050acc66ee28'
down_revision: Union[str, Sequence[str], None] = '61139cf4b2d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    sentiment_enum = sa.Enum('hostile', 'neutral', 'de_escalatory', name='sentiment')
    sentiment_enum.create(op.get_bind(), checkfirst=True)

    confidence_enum = sa.Enum('high', 'medium', 'low', name='confidencelevel')
    confidence_enum.create(op.get_bind(), checkfirst=True)

    event_category_enum = sa.Enum(
        'infiltration_attempt', 'ied', 'protest', 'troop_movement',
        'propaganda_broadcast', 'ceasefire_violation', 'supply_convoy',
        'aerial_activity', 'other', name='eventcategory'
    )
    event_category_enum.create(op.get_bind(), checkfirst=True)

    review_status_enum = sa.Enum('pending', 'accepted', 'corrected', 'rejected', name='reviewstatus')
    review_status_enum.create(op.get_bind(), checkfirst=True)

    entity_type_enum_new = sa.Enum(
        'person', 'org', 'location', 'topic', 'military_unit', 'weapon', name='entitytype'
    )
    
    entity_type_enum_new.create(op.get_bind(), checkfirst=True)

    
    op.add_column('events', sa.Column('sentiment', sentiment_enum, nullable=True))
    op.add_column('events', sa.Column('sentiment_confidence', confidence_enum, nullable=True))
    
    
    # # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'sentiment_confidence')
    op.drop_column('events', 'sentiment')
    sa.Enum(name='sentiment').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='confidencelevel').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='eventcategory').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='reviewstatus').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
