"""add confidence_scores table

Revision ID: 210d8855f6a5
Revises: eb17b4cd99f9
Create Date: 2026-08-19 15:52:15.587133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '210d8855f6a5'
down_revision: Union[str, Sequence[str], None] = 'eb17b4cd99f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('confidence_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_entity_id', sa.Integer(), nullable=True),
    sa.Column('event_classification_id', sa.Integer(), nullable=True),
    sa.Column('ner_confidence', sa.Float(), nullable=True),
    sa.Column('embedding_similarity', sa.Float(), nullable=True),
    sa.Column('source_reliability', sa.Float(), nullable=True),
    sa.Column('cross_source_agreement', sa.Float(), nullable=True),
    sa.Column('llm_confidence', sa.Float(), nullable=True),
    sa.Column('weighted_score', sa.Float(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['event_classification_id'], ['event_classifications.id'], ),
    sa.ForeignKeyConstraint(['event_entity_id'], ['event_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('confidence_scores')
    # ### end Alembic commands ###
