"""add detections, pattern templates, restriction to sector fk

Revision ID: 318a53e0ae8c
Revises: dd50f100b459
Create Date: 2026-07-31 06:29:09.566427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '318a53e0ae8c'
down_revision: Union[str, Sequence[str], None] = 'dd50f100b459'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
