"""add dedupe_hash to events

Revision ID: 33b1dfd74231
Revises: e83841138e2c
Create Date: 2026-07-24 06:44:46.018701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33b1dfd74231'
down_revision: Union[str, Sequence[str], None] = 'e83841138e2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('title', sa.String(), nullable=True))
    op.add_column('events', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('events', sa.Column('dedupe_hash', sa.String(), nullable=False))
    op.create_index(op.f('ix_events_dedupe_hash'), 'events', ['dedupe_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_dedupe_hash'), table_name='events')
    op.drop_column('events', 'dedupe_hash')
    op.drop_column('events', 'summary')
    op.drop_column('events', 'title')
    # ### end Alembic commands ###
