"""add incident_entities and sitrep_entities tables

Revision ID: 45a42eb154ef
Revises: 210d8855f6a5
Create Date: 2026-08-20 07:54:36.561654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45a42eb154ef'
down_revision: Union[str, Sequence[str], None] = '210d8855f6a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incident_entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incident_id', 'entity_id', name='uq_incident_entity')
    )
    op.create_table('sitrep_entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sitrep_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['sitrep_id'], ['sitreps.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sitrep_id', 'entity_id', name='uq_sitrep_entity')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sitrep_entities')
    op.drop_table('incident_entities')
    # ### end Alembic commands ###
