"""add incidents table

Revision ID: 61139cf4b2d1
Revises: 9fc604cede0b
Create Date: 2026-07-28 15:02:45.478190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61139cf4b2d1'
down_revision: Union[str, Sequence[str], None] = '9fc604cede0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entities', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('entities', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('entities', sa.Column('geocode_confidence', sa.String(), nullable=True))
    op.create_index(op.f('ix_entities_name'), 'entities', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entities_name'), table_name='entities')
    op.drop_column('entities', 'geocode_confidence')
    op.drop_column('entities', 'longitude')
    op.drop_column('entities', 'latitude')
    # ### end Alembic commands ###
