"""add review state to incident/sitrep entities, generalize extraction_corrections

Revision ID: 891fbfcffdcf
Revises: 45a42eb154ef
Create Date: 2026-08-20 17:39:57.955275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '891fbfcffdcf'
down_revision: Union[str, Sequence[str], None] = '45a42eb154ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extraction_corrections', sa.Column('source_table', sa.String(), nullable=False))
    op.add_column('extraction_corrections', sa.Column('source_record_id', sa.Integer(), nullable=True))
    op.add_column('incident_entities', sa.Column('review_status', sa.String(), nullable=True))
    op.add_column('incident_entities', sa.Column('reviewed_by_id', sa.Integer(), nullable=True))
    op.add_column('incident_entities', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'incident_entities', 'analysts', ['reviewed_by_id'], ['id'])
    op.add_column('sitrep_entities', sa.Column('review_status', sa.String(), nullable=True))
    op.add_column('sitrep_entities', sa.Column('reviewed_by_id', sa.Integer(), nullable=True))
    op.add_column('sitrep_entities', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'sitrep_entities', 'analysts', ['reviewed_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sitrep_entities', type_='foreignkey')
    op.drop_column('sitrep_entities', 'reviewed_at')
    op.drop_column('sitrep_entities', 'reviewed_by_id')
    op.drop_column('sitrep_entities', 'review_status')
    op.drop_constraint(None, 'incident_entities', type_='foreignkey')
    op.drop_column('incident_entities', 'reviewed_at')
    op.drop_column('incident_entities', 'reviewed_by_id')
    op.drop_column('incident_entities', 'review_status')
    op.drop_column('extraction_corrections', 'source_record_id')
    op.drop_column('extraction_corrections', 'source_table')
    # ### end Alembic commands ###
