"""add watches, alerts, notifications, reports

Revision ID: c3f77a42675e
Revises: 44e17a09cc99
Create Date: 2026-08-13 07:18:46.885294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3f77a42675e'
down_revision: Union[str, Sequence[str], None] = '44e17a09cc99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysts', sa.Column('email', sa.String(), nullable=True))
    op.add_column('analysts', sa.Column('email_alerts_enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysts', 'email_alerts_enabled')
    op.drop_column('analysts', 'email')
    # ### end Alembic commands ###
