"""add entity threat_level, annotations, relationships, sectors

Revision ID: dd50f100b459
Revises: 050acc66ee28
Create Date: 2026-07-29 07:44:57.269142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dd50f100b459'
down_revision: Union[str, Sequence[str], None] = '050acc66ee28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    threatlevel_enum = sa.Enum('low', 'medium', 'high', 'critical', name='threatlevel')
    threatlevel_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('entities', sa.Column('threat_level', threatlevel_enum, nullable=True))

    op.add_column('event_entities', sa.Column('confidence', sa.String(), nullable=True))
    op.add_column('event_entities', sa.Column('review_status', sa.String(), nullable=True))
    op.add_column('event_entities', sa.Column('reviewed_by_id', sa.Integer(), nullable=True))
    op.add_column('event_entities', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('event_entities', sa.Column('extraction_method', sa.String(), nullable=True))
    op.create_foreign_key(None, 'event_entities', 'analysts', ['reviewed_by_id'], ['id'])

    op.add_column('events', sa.Column('event_date_mentioned', sa.DateTime(timezone=True), nullable=True))
    op.add_column('events', sa.Column('sentiment_review_status', sa.String(), nullable=True))
    op.add_column('events', sa.Column('sentiment_reviewed_by_id', sa.Integer(), nullable=True))

    
    sentiment_enum = postgresql.ENUM('hostile', 'neutral', 'de_escalatory', name='sentiment', create_type=False)
    op.add_column('events', sa.Column('original_sentiment', sentiment_enum, nullable=True))

    op.alter_column('events', 'published_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.create_foreign_key(None, 'events', 'analysts', ['sentiment_reviewed_by_id'], ['id'])
     ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entities', 'threat_level')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.alter_column('events', 'published_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_column('events', 'original_sentiment')
    op.drop_column('events', 'sentiment_reviewed_by_id')
    op.drop_column('events', 'sentiment_review_status')
    op.drop_column('events', 'event_date_mentioned')
    op.drop_constraint(None, 'event_entities', type_='foreignkey')
    op.drop_column('event_entities', 'extraction_method')
    op.drop_column('event_entities', 'reviewed_at')
    op.drop_column('event_entities', 'reviewed_by_id')
    op.drop_column('event_entities', 'review_status')
    op.drop_column('event_entities', 'confidence')
    sa.Enum(name='threatlevel').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
