"""add username to analysts

Revision ID: e83841138e2c
Revises: 18ee8f16a50a
Create Date: 2026-07-23 19:01:45.004069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e83841138e2c'
down_revision: Union[str, Sequence[str], None] = '18ee8f16a50a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysts', sa.Column('username', sa.String(), nullable=False))
    op.add_column('analysts', sa.Column('hashed_password', sa.String(), nullable=False))
    op.add_column('analysts', sa.Column('role', sa.String(), nullable=True))
    op.drop_constraint(op.f('analysts_email_key'), 'analysts', type_='unique')
    op.create_index(op.f('ix_analysts_username'), 'analysts', ['username'], unique=True)
    op.drop_column('analysts', 'name')
    op.drop_column('analysts', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysts', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('analysts', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_analysts_username'), table_name='analysts')
    op.create_unique_constraint(op.f('analysts_email_key'), 'analysts', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('analysts', 'role')
    op.drop_column('analysts', 'hashed_password')
    op.drop_column('analysts', 'username')
    # ### end Alembic commands ###
