"""add confidence scoring: source reliability tracking, confidence_scores table

Revision ID: eb17b4cd99f9
Revises: d9e7ec7ebf14
Create Date: 2026-08-19 15:49:32.895253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb17b4cd99f9'
down_revision: Union[str, Sequence[str], None] = 'd9e7ec7ebf14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('correct_extractions', sa.Integer(), nullable=True))
    op.add_column('sources', sa.Column('total_reviewed_extractions', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'total_reviewed_extractions')
    op.drop_column('sources', 'correct_extractions')
    # ### end Alembic commands ###
