"""add detection fingerprint for deduplication

Revision ID: f4a1dab96db3
Revises: 4663bebbedea
Create Date: 2026-09-15 20:55:23.630664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4a1dab96db3'
down_revision: Union[str, Sequence[str], None] = '4663bebbedea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detections', sa.Column('fingerprint', sa.String(length=64), nullable=False))
    op.create_index(op.f('ix_detections_fingerprint'), 'detections', ['fingerprint'], unique=False)
    op.create_unique_constraint('uq_detection_fingerprint', 'detections', ['fingerprint'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_detection_fingerprint', 'detections', type_='unique')
    op.drop_index(op.f('ix_detections_fingerprint'), table_name='detections')
    op.drop_column('detections', 'fingerprint')
    # ### end Alembic commands ###
